config/routes.rb
Rails.application.routes.draw do
  resources :villains
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/villain.rb
class Villain < ApplicationRecord

  # validates uses rails' built in validators, or validators you've added to rails
  validates :name, :power, :adversary, :power_level, presence: true
  validates :power_level, numericality: { greater_than: 0, less_than_or_equal_to: 10 }
  # validate is used for building out custom validations
  # validates_with is used for building out validations that you want to share between models
  validate :ban_deadpool
  validates_with SkrullValidator


  private

  def ban_deadpool
    if self.name.downcase.include?("deadpool")
      self.errors.add(:name, "must not be Deadpool, who is banned from this app.")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/villains_controller.rb
class VillainsController < ApplicationController
  before_action :set_villain, only: [:show, :edit, :update, :destroy]

  # get "/villains"
  def index
    @villains = Villain.all
    render :index
  end

  def show
    render :show
  end

  # get "/villains/new"
  def new
    @villain = Villain.new
    render :new
  end

  # post "/villains"
  def create
    # @villain = Villain.create(villain_params)
    #   if @villain.valid?
    @villain = Villain.new(villain_params)
      if @villain.save
        redirect_to @villain
      else
        render :new
      end
  end

  # get "/villains/:id/edit"
  def edit
    render :edit
  end

  def update
    if @villain.update(villain_params)
      redirect_to @villain
    else
      render :edit
    end
  end

  def destroy
    @villain.destroy
    # add something here
    redirect_to villains_path
  end

  private

  def set_villain
    @villain = Villain.find(params[:id])
  end

  def villain_params
    params.require(:villain).permit(:name, :power, :adversary, :power_level)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/villains_helper.rb
module VillainsHelper

  def pluralize(number_of_items, item)
    if number_of_items > 1
      "#{number_of_items} #{item.pluralize}"
    else
      "#{number_of_items} #{item}"
    end
  end
end

app/views/layouts/_nav.html.erb
<%= link_to "Legion of Doom Roster", villains_path %> |
<%= link_to "Sign up for the Legion of Doom Today!!!", new_villain_path %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValidationsInRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= yield %>
  </body>
</html>

app/views/villains/_form.html.erb
<%= form_for @villain do |f| %>
  <% if @villain.errors.any? %>
    <p><%= "#{pluralize(@villain.errors.count, "error")} prevented this item from being saved:" %></p>
    <ul><% @villain.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
    </ul>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <%= f.label :power %>
  <%= f.text_field :power %><br/>
  <%= f.label :adversary %>
  <%= f.text_field :adversary %><br/>
  <%= f.label :power_level %>
  <%= f.number_field :power_level, in: 1..10 %><br/>
  <%= f.submit %>
<% end %>

app/views/villains/edit.html.erb
<h1>Retcon <%= @villain.name %></h1>
<%= render "form" %>

app/views/villains/index.html.erb
<h1>WELCOME TO THE LEGION OF DOOM</h1>

<h3>Current Roster</h3>
<ul><% @villains.each do |villain| %>
  <li><%= link_to villain.name, villain %></li>
<% end %>
</ul>

app/views/villains/new.html.erb
<h3>Have a bad day?</h3>
<h1>Don the Mask, Get Revenge</h1>
<%= render "form" %>

app/views/villains/show.html.erb
<h1><%= @villain.name %></h1>
<p>Power: <%= @villain.power %></p>
<p>Adversary: <%= @villain.adversary %></p>
<p>Power Level: <%= "💪 " * @villain.power_level %></p>

<%= button_to "Edit #{@villain.name}", edit_villain_path(@villain), method: :get %>
<%= button_to "Delete #{@villain.name}", @villain, method: :delete %>